# Generated by Django 6.0.3 on 2026-03-15 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The name of the dietary restriction as it appears to users.', max_length=100, unique=True)),
                ('key', models.CharField(help_text="A unique identifier for the dietary restriction, used internally. Should be lowercase and contain no spaces (e.g. 'vegan', 'gluten_free').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Dietary Restriction',
                'verbose_name_plural': 'Dietary Restrictions',
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('COACH', 'Coach'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='UserDietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietary_restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='api.dietaryrestriction')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dietary_restrictions', to='api.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='dieterary_restrictions',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='api.UserDietaryRestriction', to='api.dietaryrestriction'),
        ),
        migrations.AddIndex(
            model_name='userdietaryrestriction',
            index=models.Index(fields=['profile', 'dietary_restriction'], name='api_userdie_profile_246666_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdietaryrestriction',
            unique_together={('profile', 'dietary_restriction')},
        ),
    ]
