# Generated by Django 6.0.2 on 2026-03-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CARDIO', 'Cardio'), ('HEAVY', 'Power Lifting'), ('CABLES', 'Cable Towers'), ('MACHINES', 'Resistance Machines'), ('RAW', 'Raw Equipment')], default='RAW', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
