# Generated by Django 6.0.3 on 2026-03-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipment'),
        ('api', '0002_rename_dieterary_to_dietary'),
    ]

    operations = [
    ]
