# Generated by Django 6.0.3 on 2026-03-16 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_age_customuser_gender_customuser_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The name of the dietary restriction as it appears to users.', max_length=100, unique=True)),
                ('key', models.CharField(help_text="A unique identifier for the dietary restriction, used internally. Should be lowercase and contain no spaces (e.g. 'vegan', 'gluten_free').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Dietary Restriction',
                'verbose_name_plural': 'Dietary Restrictions',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='UserDietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietary_restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='api.dietaryrestriction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dietary_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, through='api.UserDietaryRestriction', to='api.dietaryrestriction'),
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Free-form instructions for the student.')),
                ('plan', models.JSONField(blank=True, help_text='Optional structured plan (meals, schedule, portions).', null=True)),
                ('calories_target', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('carbs_g', models.PositiveIntegerField(blank=True, null=True)),
                ('fats_g', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(help_text='Coach who created the plan', on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who receives the plan', on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Plan',
                'verbose_name_plural': 'Nutrition Plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach'], name='api_nutriti_coach_i_e5e566_idx'), models.Index(fields=['student'], name='api_nutriti_student_f08dae_idx'), models.Index(fields=['is_active', 'start_date'], name='api_nutriti_is_acti_666c81_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userdietaryrestriction',
            index=models.Index(fields=['user', 'dietary_restriction'], name='api_userdie_user_id_74769e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdietaryrestriction',
            unique_together={('user', 'dietary_restriction')},
        ),
    ]
