# Generated by Django 6.0.3 on 2026-03-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dietaryrestriction_userdietaryrestriction_and_more'),
    ]

    operations = [
        
    ]
