# Generated by Django 6.0.3 on 2026-04-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_api_message_convers_ece45b_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
